version: '3'

services:
  jekyll:
      image: jekyll/jekyll:3.8
      command: jekyll serve --force_polling --incremental --watch
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll
